### ISSUE TITLE
Enable strace for debugging

### ISSUE THREAD

**Issue by charyorde** [bitnami/bitnami-docker-postgresql#105]
Enable strace for debugging. Database sometimes in recovery mode.

```
I have no name!@postgresql-postgresql-0:/$ psql -h localhost -U postgres
psql: FATAL:  the database system is in recovery mode
```

**Comment by javsalgar** [comment]
Hi, 

I am afraid we do not include it by default. In the meantime you can create a custom version of the container that includes strace (check the Dockerfile). Could you add more details about when it is launched in recovery mode?

**Comment by charyorde** [comment]
Details here: https://github.com/helm/charts/issues/10427#issuecomment-452634224

Maybe strace is no longer needed.

**Comment by javsalgar** [comment]
I see, thanks for the link. I would wait to see if strace is that necessary to have in our containers.

**Comment by carrodher** [comment]
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
