### ISSUE TITLE
The user bitnami is currently under group 1000

### ISSUE THREAD

**Issue by svyotov** [bitnami/bitnami-docker-postgresql#109]
The user bitnami is currently under group 1000, while the docker is specified to run as 1001.

Relevant line : https://github.com/bitnami/bitnami-docker-postgresql/blob/5b9108b19cee7549621442214571585bcdbc345c/10/debian-9/Dockerfile#L40

Relevant issue: https://github.com/bitnami/minideb-extras/issues/687

**Comment by marcosbc** [comment]
Hi @svyotov, note that PostgreSQL is not actually being run by the "bitnami" user. Instead it is run by 1001 which is totally different than "bitnami".

In fact it does not have an associated group, which is why files in "/bitnami/postgresql/data" are owned by user 1001 and group root.

That's why when you connect to the container, you see something like this:

```
$ docker exec -ti 57 /bin/bash
I have no name!@570f2cdf0c9a:/$ whoami
whoami: cannot find name for user ID 1001
```

**Comment by svyotov** [comment]
Thank you for the fast reply, in that case I will close the issues.
