### ISSUE TITLE
Renaming environment variables broke kubernetes helm chart

### ISSUE THREAD

**Issue by jptissot** [bitnami/bitnami-docker-postgresql#129]
Someone renamed the environment variables of this image. The kubernetes helm chart is using 10.7.0 tag which got updated but the chart itself did not get updated. Either the chart needs to be pinned to a tag that does not change, or you need to be careful when doing breaking changes like this and not modify older tags.

**Comment by juan131** [comment]
Hi @jptissot 

No tags have been renamed recently on this image. As you can see in the Notable section below, we moved this image configuration to Bash scripts, but we didn't renamed any env. variable. 

https://github.com/bitnami/bitnami-docker-postgresql#notable-changes

The Helm chart README.md has been updated to reflect these changes too:

https://github.com/helm/charts/tree/master/stable/postgresql#upgrade

What environment variable is affecting you? 

> The kubernetes helm chart is using 10.7.0 tag which got updated but the chart itself did not get updated. 

Using "rolling tags" is not recommended at all on production environment. You can find more information in the link below:

https://docs.bitnami.com/containers/how-to/understand-rolling-tags-containers/

**Comment by jptissot** [comment]
The helm chart is using POSTGRES_USER and POSTGRES_PASSWORD but this image was just changed to support POSTGRESQL_USER and POSTGRESQL_PASSWORD.
https://github.com/helm/charts/blob/master/stable/postgresql/templates/statefulset.yaml#L141


I did not realize this was a rolling tag. My bad.
Maybe the helm chart should not default to rolling tags.
https://github.com/helm/charts/blob/master/stable/postgresql/values-production.yaml#L17

**Comment by jptissot** [comment]
I added 
``` 
postgresql:
  image:
    tag: 10.7.0-r68
```
to my values.yaml file and it fixed the issue.

**Comment by juan131** [comment]
Hi @jptissot 

As you can check in the function **postgresql_env** that you can find in the link below, **POSTGRES_USER** and **POSTGRESQL_USER** are aliases. Both formats should work.

https://github.com/bitnami/bitnami-docker-postgresql/blob/master/11/debian-9/rootfs/libpostgresql.sh#L45

Regarding the rolling tags, I agree, the **values-production.yaml** should not be using rolling tags. However, since we build the images daily, updating the **values-production.yaml** every day with the specific revision, will mean creating a new PR to helm/charts repository **every day**. I don't think it's something we can do since it'll also require releasing a patch version of the chart **every day**.

Maybe we can highlight the message explaining why rolling tags can be dangerous in production.

**Comment by jptissot** [comment]
Makes sense, it was the POSTGRESQL_PASSWORD that got me I think. I think the chart is currently broken though, as it's still using POSTGRES_PASSWORD https://github.com/helm/charts/blob/master/stable/postgresql/templates/statefulset.yaml#L141 
Yeah, maybe add a comment in the `values.production.yaml` file so others won't have this issue. 


Thank you for answering :)

**Comment by jptissot** [comment]
@juan131 Do you recommend using minideb:latest ?

**Comment by juan131** [comment]
Hi @jptissot 

They're aliases. I mean, no matter you set **POSTGRESQL_PASSWORD** or **POSTGRES_PASSWORD**, both solutions should work since the configuration scripts should be able to obtain the value to configure PostgreSQL.

> Do you recommend using minideb:latest?

The ideal scenario will be using a specific tag and have a way to track new releases. This way, you can automatically update the tag, run your tests to check nothing is broken, and then update your production environment.

**Comment by jptissot** [comment]
I don't see the POSRGRES_PASSWORD as an explicit alias in there, unless I am missing something.

**Comment by juan131** [comment]
Hi @jptissot 

It uses some "loop" to iterate over some suffixes and it declares all the aliases. Maybe the reason why it's failing is different. Could you please share the error you faced in the logs?

**Comment by jptissot** [comment]
```
ERROR ==> The password cannot be longer than 32 characters. Set the environment variable POSTGRESQL_PASSWORD with a shorter value
```

**Comment by carrodher** [comment]
@jptissot is your password longer than 32 characters?

**Comment by jptissot** [comment]
Looks like it is 34 characters. The error message got me thinking that the `POSTGRESQL_PASSWORD` environment variable was the issue. (Since the chart was setting `POSTGRES_PASSWORD` 

Did password requirements change ?

**Comment by juan131** [comment]
Hi @jptissot 

The line that's causing the error is the one below:

https://github.com/bitnami/bitnami-docker-postgresql/blob/master/10/debian-9/rootfs/libpostgresql.sh#L157

Indeed, the limit is 63 characters. I just created a PR to fix it! Thanks for reporting it

**Comment by jptissot** [comment]
Thank you and sorry about the confusion. I should have reported the error message I was seeing.

**Comment by carrodher** [comment]
No problem @jptissot, thanks for reporting the issue.
The PR was merged, please, feel free to reopen this issue if you continue facing the same behavior.
