### ISSUE TITLE
Please add postgis plugin support in the container

### ISSUE THREAD

**Issue by Amithpn** [bitnami/bitnami-docker-postgresql#148]
Im trying to install postgis on top of 10.7.0 and im getting below error:
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package postgresql-10-postgis-2.4
E: Couldn't find any package by glob 'postgresql-10-postgis-2.4'
E: Couldn't find any package by regex 'postgresql-10-postgis-2.4'
E: Unable to locate package postgresql-10-postgis-2.4-scripts
E: Couldn't find any package by glob 'postgresql-10-postgis-2.4-scripts'
E: Couldn't find any package by regex 'postgresql-10-postgis-2.4-scripts'

How do i install postgis?

**Comment by Amithpn** [comment]
How can i install postgix plugin into this container?

**Comment by carrodher** [comment]
Hi,
this issue has been reported before. You can take a look at the following issues:
- https://github.com/bitnami/bitnami-docker-postgresql/issues/85
- https://github.com/bitnami/bitnami-docker-postgresql/issues/106

Currently, we are still evaluating the impact of this change in order to take the correct decision. But it is something that we will carry out in the short term. In the meantime, can you take a look at the above links in order to check what other users did in order to install it?

In the same way, in order to unify the issues and answers, I will close this one. Please, feel free to use one of the already created issues to put your questions.
