### ISSUE TITLE
Feature request: LDAP support

### ISSUE THREAD

**Issue by AyadiAmen** [bitnami/bitnami-docker-postgresql#154]
**Description**

  I recently tried to link this image with LDAP ( inside a Kubernetes cluster )  since postgres support the LDAP authentication but when i passed the configuration in the pg_hba.conf file it turned out this image doesn't support LDAP. 

**I'm hoping you add the LDAP support to this image soon**

**Comment by alemorcuq** [comment]
Hi, @AyadiAmen.

Thank you for reporting this. We will evaluate it and come back to you when we have any news to share.

Regards,
Alejandro

**Comment by alexnuttinck** [comment]
I'm interested by this feature request too!

Got this issue:

```
2019-08-01 13:01:27.996 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2019-08-01 13:01:27.996 GMT [1] LOG:  listening on IPv6 address "::", port 5432
2019-08-01 13:01:27.998 GMT [1] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2019-08-01 13:01:28.002 GMT [1] LOG:  invalid authentication method "ldap": not supported by this build
```

@alemorcuq Is there a workaround to get ldap auth working with your Docker image ?
Do you think it can be solved by adding some libraries to the Docker image?

Thanks,

Alexandre

**Comment by alemorcuq** [comment]
Hi, @alexnuttinck.

Thank you for showing your interest in this feature! Feedback is very important to us so we can continue to improve our images. 

Unfortunately, right now we don't build PostgreSQL with LDAP support, so there's no workaround  to get it working since it has to be enabled at build time.

Nevertheless, thank you again for your feedback. I can't give you an ETA, but I'll come back to you when there's some news to share.

Regards,
Alejandro

**Comment by alexnuttinck** [comment]
@alemorcuq thanks for the answer.

Could you tell me how I can enable ldap at build time? So I can work on it while you're considering this feature request.

Regards,
Alexandre

**Comment by alemorcuq** [comment]
Hi, @alexnuttinck.

By that I mean that you have to compile PostgreSQL from source with LDAP support, so unfortunately I don't think there's an easy workaround to make it work in the current image.

Regards,
Alejandro

**Comment by alexnuttinck** [comment]
Hi, @alemorcuq,

Can you maybe share details on the build flags/options that you use?
Or can you point me to the build scripts directly?

Thanks,
Alexandre

**Comment by alemorcuq** [comment]
Hi, @alexnuttinck.

You can see the build options with `pg_config`:

```
$ pg_config --configure
'--prefix=/opt/bitnami/postgresql' '--with-libedit-preferred' '--with-openssl' '--with-libxml' '--with-libxslt' '--with-readline' '--with-icu' 'CC=gcc' 'CFLAGS=-s' 'LDFLAGS=-Wl,-rpath=/opt/bitnami/postgresql/lib -L/opt/bitnami/postgresql/lib' 'CPPFLAGS=-I/opt/bitnami/postgresql/include'
```

We don't have the compilation scripts published, however.

Regards,
Alejandro

**Comment by rafariossaa** [comment]
Hi, @AyadiAmen @alexnuttinck 
  Just to let you know that we have implemented the LDAP support in the container.
 Could you give it a try ?

Best regards
Rafael Rios Saavedra

**Comment by alexnuttinck** [comment]
@rafariossaa, thanks! I will try it soon.

**Comment by alexnuttinck** [comment]
@rafariossaa, it looks like that it works fine. I made a little test by using your [Helm Chart of postgresql](https://hub.docker.com/r/bitnami/postgresql), the [Openldap Helm Chart](https://github.com/helm/charts/tree/master/stable/openldap) and I was able to establish the connexion. It is unfortunate that there is no nice way to automatically synchronize users, groups and their memberships from LDAP to PostgreSQL. Maybe I will make a PR into the postgresql helm chart for that, by using a tool like this: https://github.com/larskanis/pg-ldap-sync.

**Comment by rafariossaa** [comment]
Hi @alexnuttinck ,
  First of all, thanks for you suggestion. 
  It is true that this kind of management can be laborious in some environments, but each admin has a preferred way of dealing with it. 
  The tool you shared seems to be without maintenance, it's been a couple of years without commits, and like a year without answering issues. To add something to the chart, it needs to be kind of official or at least very popular, and maintained. 

Best regards.
Rafael Rios Saavedra

**Comment by carrodher** [comment]
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
