### ISSUE TITLE
Master/slave terminology is unnecessarily violent and outdated

### ISSUE THREAD

**Issue by gkop** [bitnami/bitnami-docker-postgresql#175]
Hey there! I love how easy it is to set up replication with this container, thank you for developing it.

I did find however in working with the container, that the documentation and environment variables include many references to the term "slave", which evokes violent imagery and diminishes from the quality of my experience, and could make some people feel excluded from using or contributing to the project.

I was curious if you'd be open to replacing the term slave with standby as Postgres itself has done, and also perhaps replace master with primary.

Some context: https://www.postgresql.org/message-id/flat/E393EC88-377F-4C59-A67A-69F2A38D17C7@yesql.se

**Comment by juan131** [comment]
Hi @gkop 

Thanks so much for your feedback! 

We're aware of the controversy around this terminology and, indeed, there are several product (such as PostgreSQL) that moved on to other alternatives such as primary/secondary. We didn't choose this terminology but took the existing one when developing this container (and the corresponding chart) instead.

If you take a look to our new Helm chart ([PostgreSQL HA](https://github.com/bitnami/charts/tree/master/bitnami/postgresql-ha)), you'll find out that we are using this new terminology (primary/secondary) everywhere for the same reason. However, we cannot switch this terminology on the previously existing [PostgreSQL chart](https://github.com/bitnami/charts/tree/master/bitnami/postgresql-ha) since it will break backwards incompatibility and users won't be able to upgrade their charts due to switching names, labels, etc.

**Comment by kav** [comment]
@juan131 I'd be happy to PR a change for the helm chart as it's trivially easy to fallback to the legacy value key if the new terminology is not found. What is the new terminology here? Primary and replicas?

**Comment by javsalgar** [comment]
Hi,

Looking at the documentation, it would by primary and standby
