### ISSUE TITLE
How to set timezone

### ISSUE THREAD

**Issue by Wujidadi** [bitnami/bitnami-docker-postgresql#183]
I used docker compose, and in the environment field I wrote this:
```
- TZ=Asia/Taipei
```
it didn't work (it works in original pgsql container)

**Comment by bbarman4u** [comment]
@Wujidadi What was the resolution of this issue?

**Comment by dani8art** [comment]
Hi @Wujidadi, thanks for opening the issue, did you find the solution?

It should work like

```console
$ docker run --rm -ti -e TZ=Europe/Paris bitnami/postgresql date
postgresql 16:42:16.81 
postgresql 16:42:16.81 Welcome to the Bitnami postgresql container
postgresql 16:42:16.81 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgresql 16:42:16.81 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql 16:42:16.81 

Wed 19 Aug 2020 04:42:16 PM CEST
```

```console
$ docker run --rm -ti -e TZ=Asia/Taipei bitnami/postgresql date
postgresql 22:42:44.55 
postgresql 22:42:44.55 Welcome to the Bitnami postgresql container
postgresql 22:42:44.56 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgresql 22:42:44.56 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql 22:42:44.56 

Wed 19 Aug 2020 10:42:44 PM CST
```

**Comment by danydev** [comment]
I had the same problem when switching from the ["official"](https://github.com/docker-library/postgres) postgresql image to this one.
In the former, when setting the `TZ` env, postgresql.conf is updated to reflect the timezone specified in the env. In the latter you need to modify postgresql.conf yourself specifying the timezone.
You can do it with the extended configuration (i.e. mount a file in `/opt/bitnami/postgresql/conf/conf.d/timezone.conf` with `timezone = 'WHAT_YOU_ NEED'`) but since there is already `POSTGRESQL_LOG_TIMEZONE` that sets `log_timezone`, wouldn't be bad to have `POSTGRESQL_TIMEZONE` that sets `timezone`.

**Comment by dani8art** [comment]
Hi @danydev, good point! would you like to contribute to the repo with this great suggestion? If you have a chance you can open a PR and we will be happy to handle it. 

Thanks so much!

**Comment by danydev** [comment]
Sure https://github.com/bitnami/bitnami-docker-postgresql/pull/253

**Comment by dani8art** [comment]
Great!! thank you so much!

**Comment by mateusz353** [comment]
I'm trying to use `POSTGRESQL_TIMEZONE` and `POSTGRES_TIMEZONE` but TIMEZONE is still UTC. After setting variable in Dockerfile, I copy 2 init sql script to /docker-entrypoint-initdb.d/ .Maybe this is a problem. Can you check that?

**Comment by rafariossaa** [comment]
Hi,
  When you set the `xxxx_TIMEZONE` it is used by `postgresql_initialize` function. This function is called even if the initscripts are used, so that shouldn't be a problem.
  Could you check if you have the `timezone` set in the config file ? 
Ref:
- https://github.com/bitnami/bitnami-docker-postgresql/blob/2aab5bb2f88dd9e62790463ddf9565caff8fcc79/13/debian-10/rootfs/opt/bitnami/scripts/libpostgresql.sh#L631
- https://github.com/bitnami/bitnami-docker-postgresql/blob/2aab5bb2f88dd9e62790463ddf9565caff8fcc79/13/debian-10/rootfs/opt/bitnami/scripts/libpostgresql.sh#L952
