### ISSUE TITLE
Postgres pod has issues setting postgres_user and password

### ISSUE THREAD

**Issue by ramakrishnakaushik97** [bitnami/bitnami-docker-postgresql#193]
Team,

I am pulling bitnami/postgresql:12.1.0 for postgres image and passing below details as env variables as part of my deployment yaml. 

```
env:
          - name: POSTGRES_DB
            value: "db"
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "pg@111"  
```

But still getting below error in the logs after kubernetes pod is up and running.

```
2020-02-03 10:56:21.457 GMT [1] LOG:  database system is ready to accept connections
2020-02-03 10:56:46.389 GMT [212] ERROR:  relation "Licenses" does not exist at character 15
--
  | 2020-02-03 10:56:46.389 GMT [212] STATEMENT:  SELECT * FROM "Licenses" WHERE expired = false AND expiration_date > now() LIMIT 1
  | 2020-02-03 10:57:06.303 GMT [213] FATAL:  password authentication failed for user "postgres"
  | 2020-02-03 10:57:06.303 GMT [213] DETAIL:  Password does not match for user "postgres".
```

Please assist.

**Comment by andresbono** [comment]
Hi @ramakrishnakaushik97, are you persisting your database with volumes? Maybe you deployed the pod with the wrong configuration first, and now, it is not able to initialize correctly.

We tried the following with successful results:

```
docker run --rm -d --name postgresql -e POSTGRES_DB="db" -e POSTGRES_USER="postgres" -e POSTGRES_PASSWORD="pg@111" bitnami/postgresql:12.1.0

docker exec -it postgresql bash -c 'PGPASSWORD="pg@111" psql -Upostgres'
```

Maybe you can try to remove the volumes of your deployment so that you provide the correct configuration since the first start of the pod.

If that doesn't work, please give us more details about your environment and the way you are launching PostgreSQL to reproduce your issue.

**Comment by appunni-dishq** [comment]
I am facing same issue, I manage PVC myself. I deleted and recreated. I went inside the machine to check if POSTGRES_PASSWORD and POSTGRES_USER are set propely and they were there. Only thing is the order is POSTGRES_DB, POSTGRES_PASSWORD, POSTGRES_USER. But still not able to connect from with in that container

**Comment by andresbono** [comment]
Hi @appunni-dishq, can you give us more details on how are you launching the solution? Are you getting any error messages in the logs?

**Comment by appunni-dishq** [comment]
Hey I think I found the issue , I was using wrong conf I guess from an older version. I removed the conf override and it worked.

**Comment by andresbono** [comment]
Perfect, @appunni-dishq. Thanks for letting us know.

**Comment by nesies** [comment]
i experienced the same issue.
https://github.com/bitnami/bitnami-docker-postgresql/blob/master/11/debian-10/rootfs/libpostgresql.sh

postgres password is changed by postgresql_alter_postgres_user()
Which is called, only if:
- no persistance
- replication is active and current pod is "master"
- POSTGRESQL_USERNAME is set

The same behaviour for the function postgresql_create_admin_user().

It would be great to call both, even wihout replication nor persistance

**Comment by andresbono** [comment]
Hi @nesies, thanks for suggesting it, It sounds reasonable. Would you like to open a PR addressing the issue?

**Comment by andresbono** [comment]
Hi @nesies, did you see my comment in the PR?

**Comment by dany74q** [comment]
Hm - I've tackled this one as well, in a slightly different context.

I've used the bitnami helm chart to install pg on my k8s cluster, with the default created PVC;
then, I've deleted the release (which kept the PVC in my cluster, because it was automatically created by the stateful set, and not managed by helm), changed the creds via env vars, and have seen them not populate.

This is because the init script did not re-create my creds when it detected the non-empty data dir.

There's an inherent problem here, I believe - if we'd like to recreate the creds when running from a persisted volume - this means that we must use the *previously defined* credentials in order to authenticate; and we might not have access to those.

If, by chance, the previous creds match the ones passed in via the env vars, then re-creating them is redundant, as they're already there.

**Comment by andresbono** [comment]
Hi @dany74q, can't you think of any drawbacks of your approach? Couldn't the database end in an inconsistent state due to the credentials recreation?

Can you give us more technical details on how do you think the credentials recreation should be done?
