### ISSUE TITLE
InitDb fails for permission on "$POSTGRESQL_DATA_DIR" folder

### ISSUE THREAD

**Issue by mplescano** [bitnami/bitnami-docker-postgresql#217]
https://github.com/bitnami/bitnami-docker-postgresql/blob/e8453e1cd4758807ca7e0bd5f071d8183ab181cb/10/debian-10/rootfs/opt/bitnami/scripts/libpostgresql.sh#L652

it's needed to put this before:
chown "$POSTGRESQL_DAEMON_USER:$POSTGRESQL_DAEMON_GROUP" "$POSTGRESQL_DATA_DIR"

**Comment by joancafom** [comment]
Hi @mplescano ! Thanks for your comment. Could you please elaborate a little bit more on your actions so as we can reproduce the problem? 

E.g: What are you trying to do? What are the steps you followed? What is the output of the docker image? 

Thanks!

**Comment by mplescano** [comment]
I'm closingthis, because the root problem is that my container doesn't have the user 1001 created beforehand. I had to add this inside of my container and restart:
/usr/sbin/useradd -ms /bin/bash -g root 1001

**Comment by joancafom** [comment]
Thanks for your posting your solution! This Bitnami's docker image uses a non-root approach by default and relies on `USER 1001`. When the image is built, this user is also created and set to be the primary one when running the container. That is why some resources belong to this specific user, so that in runtime it can access them.

Should you have any other questions, do not hesitate to contact us again!
