### ISSUE TITLE
How to install additional postgres extensions?

### ISSUE THREAD

**Issue by mzwettler2** [bitnami/bitnami-docker-postgresql#230]
I'm looking for the best automated way to install additional postgres extensions not included with the bitname image?

Any idea?

- Markus

**Comment by joancafom** [comment]
Hi Markus @mzwettler2 

Thanks for your issue! This image allows the of bash scripts and sql files when the container is executed, so I am thinking that a possible solution could be writing a script that automates the installation process for you. You may find this [section](https://github.com/bitnami/bitnami-docker-postgresql#configuration) in the README very helpful. What do you think?

Thanks!

**Comment by mzwettler2** [comment]
Hi,

1.) Bitnami uses a non-default pg location of "/bitnami/postgres". How should I install *.deb packages with apt install in such a non-default location?
2.) How should I steer the installation order using the bitnami "docker-entrypoint-initdb.d" mechanism? 1. shell script to install the *.deb package. + 2. sql script to create the extension.

-Markus

**Comment by joancafom** [comment]
Hi @mzwettler2 

1) As you are installing system packages, I think there shouldn't any problems on running apt-install and `postgres` recognizing them. For instance, I have just quickly tried installing [PostGIS](https://postgis.net/):

```console
$ docker-compose up -d
$ docker exec -u root -it bitnami-docker-postgresql_postgresql_1 bash
$ install_packages postgis
$ psql -U postgres
```
```console
postgres=# CREATE EXTENSION postgis;
SECREATE EXTENSION
postgres=# SELECT postgis_version();
            postgis_version
---------------------------------------
 2.5 USE_GEOS=1 USE_PROJ=1 USE_STATS=1
(1 row)
```

A quick note on `install_packages`, it is a wrapper we provide in our containers in order to do some commands at commands, but you could do `apt-get update && apt-get install postgis -y` as well and it should also work.

2) Yes I think it should be the way of proceeding. However, there is a small caveat on this. Installing packages is an action that requires some privilege, but this container is non-root by default. You may need to run the container as root in order to successfully achieve that action, I don't know if that suits your case.

Hope it helps, thanks!

**Comment by mzwettler2** [comment]
Hi,

Nope.

You are using and compiling the postgres source code into your individual postgres location "/opt/bitnami/postgresql". apt install will install into the postgres debian default location "/usr/lib/postgresql".

Just try to install "postgresql-12-cron". You will find it afterwards under "/usr/lib/postgresql/12/lib" while it should be below "/opt/bitnami/postgresql/lib". This does not work!

The only possibility I see is to work analogous your "libcomponent.sh". Compile the source code and copy it in. But this is very complex and laborious.

-Markus

**Comment by joancafom** [comment]
Hi @mzwettler2 

Yes, you are right. Current container does provide built-in support for postgis, that is why my workaround works. Compiling the source code and setting up the right configuration parameters should do the trick as you said, but maybe it does not fit your requirements. Right now I do not see another fully working alternative. You can see how other users tackled the problem when Postgis was not provided by default here #85.

Best regards and thanks for your issue.

**Comment by mzwettler2** [comment]
Hi,
I think the only reason you are using and installing from source code is to locate the binaries into your Bitnami directory. Ok, you are creating some kind of Bitnami installation standard with it. But this makes it very complex and laborious for any Bitnami user to extend the image. No easy apt install anymore. Wouldn't it be better and easier for anyone if you would simply create your image from *deb packages with apt install into the normal Debian default locations?
-Markus

**Comment by joancafom** [comment]
Hey @mzwettler2

Bitnami compiles its own binaries with the aim of delivering the latest (and some other) versions of several assets. We also automate configuration and usually include most popular extensions so as to make users benefit from an easy-to-use product. Using "/opt" path is not arbitrary, but a choice due to the fact that this directory is where thirdparty library (like our own ones) should be installed. Furthermore, another important aspect is that using the default location may lead to some conflicts with the original system packages.

You mentioned before you were trying to install `postgresql-12-cron`. Is that correct? Maybe we can evaluate adding it to our image 😁

Thanks!

**Comment by mzwettler2** [comment]
Hi,

Please don't forget that your image will grow larger and larger the more extensions you add.  Finally, you will have very large images with tons of extensions not really used by most customers.

I think, it would be much more affordable to create some kind of easy extend-it-yourself image. Using default debian packages would be such an easy way. I don't see your point about conflicts with original system packages, especially as we are talking about precreated images.

-Markus

**Comment by joancafom** [comment]
Hi!

Yes, we are aware that the image will grow larger by adding lots of extensions, hence we usually pack the most popular ones to reduce this side-effect. When a user requests a new change like this we perform an evaluation that will take into account those details and eventually determine the feasibility of the modification.

Providing an image that flawlessly works with system packages is a wonderful feature for sure, but I am afraid this is not Bitnami's goals and workflow. Not only do we compile our own binaries, we provide with automation in configuration, and that means in fact that we are producing a thirdparty asset (hence, we use the `/opt` path). The goal is not to replace the main product but to enhance it and deliver the latest version of it (while sometimes providing support for other ones as well). In addition, this automation layer is designed with this whole idea in mind, and more than certain, conflicts may arise if someone plans to change this.

I see your point and I understand your concerns, but I think I do not see a strong alignment with our mission here. We love to have feedback from our users and we always take them into account, so thank so much for your issue!

**Comment by mzwettler2** [comment]
Hi,

It's all about the installation path at the end. Debian vs. individual. The debian path would not contradict your goals nor any automation but adding additional value to your asset. Moreover, using existing defaults than creating new ones looks always better to me.

-Markus

**Comment by pranithan-kang** [comment]
Hi,

I would like to know the conclusion about how to install an extension. Is it possible or too complex for user like me? My purpose is to install the extension plpython3u.

Thank you,

**Comment by jotamartos** [comment]
Hi @pranithan-kang,

As discussed in this thread, we compile our own binaries (the PostgreSQL one and its extensions) and that's why the system's packages (apt command) do not work when using our solution.  Including this package will require to build the PostgreSQL package from scratch with the required parameters and that's not straightforward. 

I'm sorry to say that including this extension in our solution is not in our roadmap but we will take it in mind when considering extra packages to include in our solution.

Thanks
