### ISSUE TITLE
Installing PostgreSQL extension

### ISSUE THREAD

**Issue by clementtournier** [bitnami/bitnami-docker-postgresql#249]
Hello,

Is there any way to install a custom Postgresql extension on bitnami 9.6 image version ?

We were able to edit the image, everything was ok until we tried to install the deb file using APT.

The installation always fails because it has a dependency on the *postgresql-9.6* package which is not listed using *dpkg*.

```
The following packages have unmet dependencies:
 postgresql-9.6-pglogical : Depends: postgresql-9.6 (>= 9.6.10) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

I imagine this is normal behavior and is the inner workings of bitnami postgresql.

Is there a workaround to install an external extension ?

Thank you,

**Comment by marcosbc** [comment]
Hi @clementtournier, it should be possible to do it if you compile the module like this:

```
$ install_packages build-essential libssl-dev
$ make PG_CONFIG=/opt/bitnami/postgresql/bin/pg_config
$ make PG_CONFIG=/opt/bitnami/postgresql/bin/pg_config install
```

However, we just noticed thanks to this issue that the Bitnami PostgreSQL container lacks required static libraries such as `libpgcommon.a`, making this process fail. I've created an internal task to fix this issue and will update with any progress.

**Comment by clementtournier** [comment]
Hello @marcosbc ,

From where should we run the compilation ? Can't find configure script or makefile.
Are the sources files available ?

```
make PG_CONFIG=/opt/bitnami/postgresql/bin/pg_config

make: *** No targets specified and no makefile found.  Stop.
```

**Comment by marcosbc** [comment]
Hi @clementtournier, we were using the pglogical sources from here: https://github.com/2ndQuadrant/pglogical

Once pending PostgreSQL libraries are added (until that happens this won't work), you'd need to extract the latest release and run the commands inside the extracted folder.

We keep looking into this. Unfortunately it seems not to be trivial because adding all .a files seem to add +200M to the container image size. We're checking if it would be possible to include only the libpgcommon.a and related files that are not so big.

However, we cannot guarantee that we'll be able to enable extension building support for the container image due to the last findings, it looks like not even the official PostgreSQL Docker image supports that. We'll do our best, though, and get back to you with any update.

If it turns out we cannot add support for building extensions, we'd be interested in knowing the extensions you wanted to install apart from pglogical. That way we can evaluate whether it would make sense to add them on our side to PostgreSQL natively.

**Comment by marcosbc** [comment]
@clementtournier We've implemented this feature now, and you should be able to compile modules locally for your PostgreSQL image.

Could you take a look at the following Bitnami PostgreSQL container releases?

* 9.6.19-debian-10-r45
* 10.14.0-debian-10-r44
* 11.9.0-debian-10-r38
* 12.4.0-debian-10-r43

To compile the module follow these steps:

```
$ install_packages build-essential libssl-dev libxslt1-dev libxml2-dev zlib1g-dev libedit-dev
$ curl -JL -o /tmp/pglogical.tar.gz https://github.com/2ndQuadrant/pglogical/archive/REL2_3_2.tar.gz
$ tar xzf /tmp/pglogical.tar.gz -C /tmp
$ make -C /tmp/pglogical-REL2_3_2 PG_CONFIG=/opt/bitnami/postgresql/bin/pg_config
$ make -C /tmp/pglogical-REL2_3_2 PG_CONFIG=/opt/bitnami/postgresql/bin/pg_config install
```

Hope it works!

**Comment by clementtournier** [comment]
Hello @marcosbc ,

It seems to work more. Thank you.
Now we need to modify the shared_preload_libraries in order to be able to make the extension usable on the database

```
postgres=# CREATE EXTENSION pglogical;
ERROR:  pglogical is not in shared_preload_libraries
```

**Comment by marcosbc** [comment]
Hi @clementtournier, for that you can use the environment variable as described here: https://github.com/bitnami/bitnami-docker-postgresql#preloading-shared-libraries

**Comment by clementtournier** [comment]
Hi @marcosbc 

Pglogical extension was successfully installed and it is now possible to create a logical replication node. 
We'll use it to replicate some specifics tables to AWS RDS (PostgreSQL 9.6.X). We still have to edit the postgresql.conf and pg_hba.conf but I saw in the bitnami documentatio nthat it should be possible.

This issue is now fixed for me. Thank's a lot.

**Comment by marcosbc** [comment]
Thanks for sharing! I'm glad it worked for you. I'll proceed to close this issue.
