### ISSUE TITLE
CVE issues regarding libsqlite3-0

### ISSUE THREAD

**Issue by rbissey-axway** [bitnami/bitnami-docker-postgresql#250]
**Description**

Twistlock reports some security issues:

> CVE-2020-13630: ext/fts3/fts3.c in SQLite before 3.32.0 has a use-after-free in fts3EvalNextRow, related to the snippet feature.

> CVE-2020-13871: SQLite 3.32.2 has a use-after-free in resetAccumulator in select.c because the parse tree rewrite for window functions is too late.

> CVE-2020-13632: ext/fts3/fts3_snippet.c in SQLite before 3.32.0 has a NULL pointer dereference via a crafted matchinfo() query.

> CVE-2020-13631: SQLite before 3.32.0 allows a virtual table to be renamed to the name of one of its shadow tables, related to alter.c and build.c.

This package has been fixed for Debian 9 but not yet for Debian 10: https://security-tracker.debian.org/tracker/source-package/sqlite3

Are you planning to do something specific about the issues above, or will you wait for the CVE to be fixed on Debian-10?
Thanks for your reply.

**Version**

bitnami/postgresql:latest

**Comment by carrodher** [comment]
Hi, as you rightly said, those CVEs are still open (not fixed) by the distro itself. Until Debian releases a new version of the library patching this CVE, there is nothing we (Bitnami) can do on our side. We build the images on a daily basis to ensure that as soon as there are patches available, the images include them. However, we can do anything until the distro (Debian in this case) patches them.

You can find more info about the CVE policy that we use for Containers & Helm Charts at https://docs.bitnami.com/kubernetes/open-cve-policy/

**Comment by rbissey-axway** [comment]
Thanks for this feedback!

**Comment by bharadwaj145** [comment]
@carrodher With reference from https://security-tracker.debian.org/tracker/CVE-2019-8457, the issue seems to be fixed in the upstream debian:buster image. But the bitnami docker image has a reference installing libsqlite3-0 explicitly.
Ref: https://github.com/bitnami/bitnami-docker-postgresql/blob/master/12/debian-10/Dockerfile#L11

Please correct me if I am wrong.

**Comment by bharadwaj145** [comment]
@rbissey-axway Could you please reopen this issue?

**Comment by carrodher** [comment]
The `install_packages` function is a wrapper to use the packaging system of the different distros. In the case of Debian, `install_package` executes `apt` in the background in order to install the Debian packages.

[Here](https://quay.io/repository/bitnami/postgresql/manifest/sha256:68fe7033afa0ac760d7757181b6332644ee64b46a60c66d0e1cae966abcb6860?tab=vulnerabilities) you can find the report for `bitnami/postgresql:latest` (you can see other tags by navigating in this UI). At this very moment, there are 99 CVEs reported but 0 fixable, as mentioned above, in that case, there is nothing to do on our side.

In the same way, running trivy via CLI there are no unfixed CVEs:
```console
$ trivy --ignore-unfixed --vuln-type os bitnami/postgresql:latest
2021-09-17T15:13:40.370Z	INFO	Detecting Debian vulnerabilities...

bitnami/postgresql:latest (debian 10.10)
========================================
Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
```

About the specific CVE, you are mentioning it doesn't appear, see
```console
$ trivy --ignore-unfixed --vuln-type os bitnami/postgresql:latest | grep "2019-8457"
```
If it is already fixed in the distro package it should be included in the latest versions of the images since we build the image on a daily basis by installing the latest version of the packages.

**Comment by rbissey-axway** [comment]
@bharadwaj145 As you can see, the last docker image (10.18.0-debian-10-r35) contains the correct patched version for **libsqlite3-0**:

> $apt-cache policy libsqlite3-0
> libsqlite3-0:
>   Installed: 3.27.2-3+deb10u1
>   Candidate: 3.27.2-3+deb10u1
