### ISSUE TITLE
Lack of ogr-fdw

### ISSUE THREAD

**Issue by g00ntar** [bitnami/bitnami-docker-postgresql#275]
Can you add ogr-fdw ?

**Comment by carrodher** [comment]
Thanks for the suggestion. Please, can you provide more info about this extension? What is your use case, how do you expect to use it, what is the official place where the source code is hosted and maintained, etc. In this way, our team can evaluate the feasibility of adding it to the default image.

**Comment by g00ntar** [comment]
### PostgreSQL [OGR](https://gdal.org/index.html) Foreign Data Wrapper
_I assume there are some people which uses your image as PostGIS db (because of added PostGIS funcionality), so this plugin can be very usefull for them._

As name say it is _foreign data wrapper_ which allows to query with SQL (and use _geo functions_ as it warps ogr) external data in [formats which ogr can read](https://gdal.org/drivers/vector/index.html) like e.g. ESRI FileGDB or (which is most important for me) WFS. With WFS service where data is frequently changed is very usefull to have ability to not load this data every time to DB and only crate materialized view of them.

In ubuntu it is in universe reposistory with name postgresql-${PG_MAJOR_VERSION}-ogr-fdw.
As I see on [Debian -- Package Search](https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=ogr-fdw) for debian are avaiable postgresql-11-ogr-fdw for buster and postgresql-13-ogr-fdw for bullseye with lack of postgresql-12-ogr-fdw at all.

[Github repo](https://github.com/pramsey/pgsql-ogr-fdw)

**Comment by carrodher** [comment]
Thanks, I am going to create an internal task to evaluate this proposal, in the meantime, you can clone this repository and build your own postgresql image by extending this one adding the required changes to the _Dockerfile_

**Comment by carrodher** [comment]
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
