### ISSUE TITLE
JIT not available on PG12 debian-10

### ISSUE THREAD

**Issue by mpaletou** [bitnami/bitnami-docker-postgresql#297]
**Description**

JIT packages are installed but not available (tested on 12/debian-10 image) from PostgreSQL.

**Steps to reproduce the issue:**

1. Run sample database `docker run --name postgresql -e POSTGRESQL_USERNAME=my_user -e POSTGRESQL_PASSWORD=password123 -e POSTGRESQL_DATABASE=my_database -p 5432:5432 bitnami/postgresql:latest`
2. Launch `SELECT pg_jit_available();` query

**Describe the results you received:**

pg_jit_available is false

**Describe the results you expected:**

pg_jit_available is true

**Additional information you deem important (e.g. issue happens only occasionally):**

I didn't tested it on other database versions (only with 12/debian-10).

LLVM seems to be installed as `dpkg -l | grep llvm` result is: libllvm7:amd64                       1:7.0.1-8+deb10u2           amd64

**Comment by alvneiayu** [comment]
hi @Cafe31 

It seems that JIT is disabled by default. Here, you can find the pgsql-hackers discussion referenced:

https://www.postgresql.org/message-id/20180914222657.mw25esrzbcnu6qlu@alap3.anarazel.de

and here, I found a small guide to enable JIT (maybe it can help you):

https://www.percona.com/blog/2018/11/19/installing-and-configuring-jit-in-postgresql-11/

Thanks a lot and let me know if I can help you with something else.

Álvaro

**Comment by Cafe31** [comment]
Hi @alvneiayu 

I thank you for your answer, however it does not help me unfortunately.

Indeed, there is a distinction between having JIT enabled and having JIT available.

On Postgres 12, JIT is **enabled** by default `(SHOW jit;` return on).

However, JIT is **not available** (`SELECT pg_jit_available();` return false).

On official Postgres 12 images, JIT is **available** and **enabled** by default.

With **Bitnami Postgres's 12** image, JIT is **enabled** but not available by default

To make it available, you have to compile Postgres with the `--with-llvm` option, which doesn't seem to be the case. After investigations, I don't think I have the necessary access to propose this fix by myself.

**Comment by Cafe31** [comment]
As you can see in PostgreSQL documentation, jit can be enabled even if it is not available:
https://www.postgresql.org/docs/12/jit-decision.html

**Comment by alvneiayu** [comment]
hi @Cafe31 

oh, sorry for the misunderstanding. Thanks a lot for the information shared. Let me check it.

Thanks again.

Álvaro

**Comment by alvneiayu** [comment]
hi @Cafe31 

I created an internal task to investigate about this problem and added it to the backlog. I am not able to give you an ETA. We will update this thread once we have news.

Thanks a lot

Álvaro

**Comment by Cafe31** [comment]
Hi @alvneiayu,

I thank you for following up on this issue.

Hoping this issue will be corrected soon !

**Comment by alvneiayu** [comment]
Hi @Cafe31 

Thanks for your help.

Álvaro

**Comment by Cafe31** [comment]
Hi everyone,

For those who want a **workaround** while waiting for this issue to be addressed:
- Compile PostgreSQL from sources in order to generate llvmjit.so file or download a compiled one [here](https://bitnami-custom-builds.s3.fr-par.scw.cloud/llvmjit.so)
- Copy this .so file in /opt/bitnami/postgresql/lib
- Install llvm-7-dev package

Here is a working example of Dockerfile layer:
```
RUN install_packages llvm-7-dev \
        && curl -o /opt/bitnami/postgresql/lib/llvmjit.so https://bitnami-custom-builds.s3.fr-par.scw.cloud/llvmjit.so \
        && chmod 755 /opt/bitnami/postgresql/lib/llvmjit.so \
        && chown 0:1001 /opt/bitnami/postgresql/lib/llvmjit.so
```
        
Else you can generate llvmjit.so by yourself using following Dockerfile (will be available in _/tmp/postgresql_build/src/backend/jit/llvm/llvmjit.so_):
```
FROM bitnami/postgresql:12-debian-10 AS pg-builder

ENV POSTGRESQL_VERSION 12.7

USER root

RUN apt update && apt install -y --no-install-recommends build-essential clang libreadline-dev zlib1g-dev llvm-7-dev \
        && cd /tmp \
        && curl -o /tmp/postgresql-${POSTGRESQL_VERSION}.tar.gz https://ftp.postgresql.org/pub/source/v${POSTGRESQL_VERSION}/postgresql-${POSTGRESQL_VERSION}.tar.gz \
        && tar xf /tmp/postgresql-${POSTGRESQL_VERSION}.tar.gz \
        && mkdir -p /tmp/postgresql_build && cd /tmp/postgresql_build \
        && /tmp/postgresql-12.7/configure  --with-llvm \
        && make
```

**Comment by alvneiayu** [comment]
hi @Cafe31 

Thanks a lot for sharing your workaround. It will be really helpful for the community.

Again, thanks

Álvaro

**Comment by carrodher** [comment]
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
