### ISSUE TITLE
Bitnami/postgesql CVE Issue 

### ISSUE THREAD

**Issue by jweaver4** [bitnami/bitnami-docker-postgresql#314]
**Description**

I hope this is the right place for this issue.  Using Azure Container Registry am receiving high vulnerability for bitnami/postresql: 13.x.x and 14.x.x. "GNU Bash Privilege Escalation Vulnerability for Debian".  Bash packages bullseye, bookworm and sid have been fixed according to the CVE. stretch and buster releases have not.  I notice that the Dockerfile uses "FROM docker.io/bitnami/minideb:buster".  

**Steps to reproduce the issue in **

1. Example: docker push bitnami/postgresql:14.1.0-debian-10-r22 to ACR
2. check the security vulnerabilities report.

**Describe the results you received:**

GNU Bash Privilege Escalation Vulnerability for Debian, CVE-2019-18276

**Describe the results you expected:**

No "High" vulnerabilities.

Questions;
1. Is there a bullseye, bookworm or sid version forthcoming?  These have been remediated.  Maybe it is something else?

**Comment by carrodher** [comment]
- Running CVE scanner with `--ignore-unfixed` flag
```console
$ trivy --ignore-unfixed --vuln-type os bitnami/postgresql:14.1.0-debian-10-r22
2021-12-08T08:57:00.984Z	INFO	Detected OS: debian
2021-12-08T08:57:00.984Z	INFO	Detecting Debian vulnerabilities...

bitnami/postgresql:14.1.0-debian-10-r22 (debian 10.11)
======================================================
Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
```

- Running CVE scanner without `--ignore-unfixed` flag
```console
$ trivy --vuln-type os bitnami/postgresql:14.1.0-debian-10-r22
2021-12-08T08:55:28.699Z	INFO	Detected OS: debian
2021-12-08T08:55:28.699Z	INFO	Detecting Debian vulnerabilities...

bitnami/postgresql:14.1.0-debian-10-r22 (debian 10.11)
======================================================
Total: 190 (UNKNOWN: 0, LOW: 130, MEDIUM: 21, HIGH: 31, CRITICAL: 8)

+------------------+------------------+----------+------------------------+---------------+--------------------------------------------------------------+
|     LIBRARY      | VULNERABILITY ID | SEVERITY |   INSTALLED VERSION    | FIXED VERSION |                            TITLE                             |
+------------------+------------------+----------+------------------------+---------------+--------------------------------------------------------------+
| apt              | CVE-2011-3374    | LOW      | 1.8.2.3                |               | It was found that apt-key in apt,                            |
|                  |                  |          |                        |               | all versions, do not correctly...                            |
|                  |                  |          |                        |               | -->avd.aquasec.com/nvd/cve-2011-3374                         |
+------------------+------------------+          +------------------------+---------------+--------------------------------------------------------------+
| bash             | CVE-2019-18276   |          | 5.0-4                  |               | bash: when effective UID is not                              |
|                  |                  |          |                        |               | equal to its real UID the...                                 |
|                  |                  |          |                        |               | -->avd.aquasec.com/nvd/cve-2019-18276                        |
+------------------+------------------+          +------------------------+---------------+--------------------------------------------------------------+
...
```

From the previous logs we can see there are no CVEs fixed in the mentioned image, there are 190 CVEs but not fixed by the distro.

A similar result can be found by using the [Quay scanner](https://quay.io/repository/bitnami/postgresql/manifest/sha256:8109654f6bd7a2ac9e8f7491bd6b4171f4680fc4439b20166472b17464094979?tab=vulnerabilities):

![Screenshot 2021-12-08 at 09 56 37](https://user-images.githubusercontent.com/13216600/145179224-5989b11c-2129-4cd9-b670-31d808f0a069.png)

The above screenshot is marking the "Only show fixable" checkbox and there are no fixable CVEs reported in the image. Unchecking the checkbox, 98 vulnerabilities appear but it is something we can't fix until the package is updated in the distro itself.

We will move the Bitnami catalog to Debian 11 Bullseye in the short/mid-term, but at this moment there is nothing we can do to solve this kind of non-fix CVEs in the distro

**Comment by jweaver4** [comment]
Thank you for your reply. I will be sure track non-fixable vulnerabilities.
