### ISSUE TITLE
Vulnerabilities included in base image - debian 11 bullseye support

### ISSUE THREAD

**Issue by aru-trackunit** [bitnami/bitnami-docker-postgresql#323]
**Snyk found vulnerabilities in base image used in bitnami-docker-postgresql docker image**

It also suggests that in order to fix those vulnerabilities would be great to upgrade to bullseye.

Are you planning to upgrade base image?

Thank you

**Comment by javsalgar** [comment]
Hi. We have plans to upgrade the base image, but in not in the immediate short term. As soon as there are updates that fix the issue in Debian 10, a new revision of the image will be released.

**Comment by carrodher** [comment]
Hi, unfortunately, those security vulnerabilities are not fixed by the OS or the application itself, so although we built the images on a daily basis, this kind of CVE will be reported while there is not a new version patching the issue in the OS or the application.

You can find more info in [this blog post](https://docs.bitnami.com/kubernetes/open-cve-policy/).
[This CVE scan report](https://quay.io/repository/bitnami/postgresql?tab=tags) contains a security report with all open CVEs. To get the list of actionable security issues, find the "latest" tag, click the vulnerability report link under the corresponding "Security scan" field and then select the "Only show fixable" filter on the next page.

The Bitnami Open Source/Community Catalog is based on Debian but Bitnami/VMware provides a custom container and Helm Charts catalog based on the desired base image (generic distro or custom golden image) through [VMware Tanzu Application Catalog](https://tanzu.vmware.com/application-catalog).
