### ISSUE TITLE
Hot enable and disable Slave Replication

### ISSUE THREAD

**Issue by ramzcode** [bitnami/bitnami-docker-postgresql#344]
### Name and Version

bitnami/postgres

### What is the problem this feature will solve?

To enable or disable slave or replication

### What is the feature you are proposing to solve the problem?

To enable or disable a postgres as a slave without restarting the container

**Comment by javsalgar** [comment]
Hi,

I imagine that you would need entering the container and perform the steps manually inside the psql console.

**Comment by ramzcode** [comment]
Can you give me the steps so that i can try and let know the results

**Comment by javsalgar** [comment]
Hi,

In order to enter the container you would need to execute:

```
kubectl get pods 
```

There you would see the ID of the container you want to access. Copy the id and then execute:

```
kubectl exec -ti ID_OF_THE_POD -- bash 
```

There, you would be inside the container. Inside you can execute

```
PGPASSWORD=$POSTGRESQL_PASSWORD psql -U postgres 
```

Inside the PostgreSQL console, you could execute the commands to disable replication. I don't exactly know the commands, but I found this link that could be useful to you:

https://www.postgresql.org/message-id/CAKgWO9JXan4iAHHCq5iN9aBENxBRaWmf=y673NUghiOAHfxBMg@mail.gmail.com

**Comment by ramzcode** [comment]
Thanks will give a try and let know the status
