### ISSUE TITLE
Master is a single point of failure

### ISSUE THREAD

**Issue by kuznero** [bitnami/bitnami-docker-postgresql#59]
Nice job! But I have a question - it seems as if this setup is having single point of failure - its master node. As you mention in the README, it is possible to configure one of the salves to become a new master and you would also need to restart all other slaves to become aware of a new master. That introduces potentially big downtime in cases when master goes down.

Is there any way to have multiple masters as well as multiple slaves with PostgreSQL such that it is possible to overcome this single point of failure?

There is a bit of solutions that are currently available to make multi-master consistent clustering [here](https://wiki.postgresql.org/wiki/Replication,_Clustering,_and_Connection_Pooling).

**Comment by sameersbn** [comment]
> Is there any way to have multiple masters as well as multiple slaves with PostgreSQL such that it is possible to overcome this single point of failure?

At the moment the image allows users to setup the postgresql's builtin master-slave streaming replication. It is correct that if the master goes down, every other slave will have to be restarted after promoting one one the existing slave to become the master.

A probable way to alleviate this problem is  by cascading the replication setup where,

 - `slave01` replicates from the `master`
 - `slave02` replicates from `slave01`
 - `slave03` replicates from `slave02` and so on...

So it the `master` fails, only `slave01` would need to be promoted to become the master and theoretically rest of the cluster should operate normally. But unfortunately my initial tests reveal that the replication breaks when one of the slaves is promoted to become the master. I am currently investigating if this is something that we can fix in our default configurations.

Let us know your insights and thoughts.
