### ISSUE TITLE
SSL support through env variables?

### ISSUE THREAD

**Issue by DracoMilesX** [bitnami/bitnami-docker-postgresql#71]
I was wondering if it was possible to add the option to enable SSL support through env variables?

**Comment by javsalgar** [comment]
Hi, 

Thanks for opening the issue. We are currently studying how to implement it, but not in the short term. A possibility that comes to mind would be having a environment variable to activate SSL (something like `ENABLE_SSL`) and be able to mount your certificate in a specific location. Would something like that work for your use case?

**Comment by DracoMilesX** [comment]
Hi,

Yes the would indeed work for my current use case.

**Comment by carrodher** [comment]
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
