### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by swistaczek** [bitnami/bitnami-docker-postgresql#98]
Hey,
Is there any easy way to achieve PostgreSQL instance with available SSL (like in [aptiable PostgreSQL docker image](https://github.com/aptible/docker-postgresql))?

**Comment by andresbono** [comment]
Hi @swistaczek, we have not tested this feature before. In the _PostgreSQL_ configuration file you have a section on _SSL_ settings:

`/opt/bitnami/postgresql/conf/postgresql.conf`
```
# - SSL -

#ssl = off
#ssl_ca_file = ''
#ssl_cert_file = 'server.crt'
#ssl_crl_file = ''
#ssl_key_file = 'server.key'
#ssl_ciphers = 'HIGH:MEDIUM:+3DES:!aNULL' # allowed SSL ciphers
#ssl_prefer_server_ciphers = on
#ssl_ecdh_curve = 'prime256v1'
#ssl_dh_params_file = ''
#ssl_passphrase_command = ''
#ssl_passphrase_command_supports_reload = off
```

You can change them to make _PostgreSQL_ work with _SSL_ enabled. You can take a look at the official documentation about it: https://www.postgresql.org/docs/current/ssl-tcp.html.

In order to persist the changes that you make in the configuration file you will need to create a volume for it: [Configuration file](https://github.com/bitnami/bitnami-docker-postgresql#user-content-configuration-file).

As you will need to have two _SSL_ files (`server.crt` and `server.key`) in the container, you probably want to mount them as volumes too, in the same way you should do with the configuration file.

---

These are just rough steps to make _SSL_ work with `PostgreSQL`. Please let us know if you can make it work.

I see this as an interesting feature to support by our container. What do you think? cc @javsalgar @carrodher.

Best,
-Andrés B.

**Comment by khatkarr** [comment]
not able to SSL config using env variables.

**Comment by andresbono** [comment]
Hi @khatkarr, what environment variables did you use? Note that this container doesn't support automatic configuration for SSL yet. See https://github.com/bitnami/bitnami-docker-postgresql/issues/98#issuecomment-444014737.

**Comment by khatkarr** [comment]
@andresbono I tried doing that. The issue is now to fix the permissions of those certificate files.
There is no user in container. Not even `postgres`.
`
I have no name!@5dddd95deed7:/$ sudo
bash: sudo: command not found
I have no name!@5dddd95deed7:/$ su
su: Cannot determine your user name.
I have no name!@5dddd95deed7:/$ who
I have no name!@5dddd95deed7:/$ echo $USER

I have no name!@5dddd95deed7:/$ 
`

**Comment by andresbono** [comment]
How are you providing the certificates? Are you mounting them as volumes for the container?

About the env-var to get the data directory, you can use `POSTGRESQL_DATA_DIR`:
```
$ docker run --rm bitnami/postgresql env | grep POSTGRESQL_DATA_DIR
POSTGRESQL_DATA_DIR=/bitnami/postgresql/data
```

**Comment by khatkarr** [comment]
@andresbono Following is my Dockerfile that I am using for now and its working:
```
FROM bitnami/postgresql
#To avoid permission issues on non-linux systems.
COPY ca /ca
COPY ssl.conf /opt/bitnami/postgresql/conf/conf.d/ssl.conf
```
sss.conf, file permissions set to 777:
```
# - SSL -

ssl = on
ssl_cert_file = '/ca/server.crt'
ssl_key_file = '/ca/server.key'
#permissions for server.key set to group read-write and no other change on host.
```

**Comment by andresbono** [comment]
Hi @khatkarr, that's great! Did you need to do any other major change in the configuration? We will try to integrate the SSL support in our image.

**Comment by khatkarr** [comment]
@andresbono I dit not make any other change...only issue is that setting up right permissions on certs files and config file otherwise db server in container shutdown itself.

The base Debian image needs to be updated as it contains many packages that has security vaulranibility when docker image was scanned for security issues.

**Comment by andresbono** [comment]
Good to know, @khatkar.

About the Debian base image, we build it regularly. As soon as the official Debian repositories add new packages, the images will get released automatically with the new version of the components.

**Comment by carrodher** [comment]
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
